<?php
function add_paystub_get_pages($path=''){
	return array(
	'modern'=>	array("Modern", $path.'add_modern_paystub_preview.php'),
//	'neat'=>	array("Neat Paystub", $path.'add_neat_paystub_preview.php'),
//    'corp'=>	array("Corporate Paystub", $path.'add_corp_paystub_preview.php'),
//	'basic'=>	array("Basic Paystub", $path.'add_basic_paystub_preview.php'),
//	'tstub'=>	array("T-Stub", $path.'add_tstub_paystub_preview.php'),
//	'w2'=>		array("W-2 IRS", $path.'add_w2_paystub_preview.php'),
//	'1099'=>	array("1099", $path.'add_1099_paystub_preview.php'),
	);
}
?>